argocd: Plugin to perform various actions on ArgoCD
walmartlabs/concord-plugins pull request #97
Opened 2022-09-15 13:55 UTC by jchikatur

2022-09-15 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/walmartlabs/concord-plugins?pullRequest=97) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/walmartlabs/concord-plugins?pullRequest=97) before we can accept your contribution.<br/><hr/>**Jayanth C A** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/walmartlabs/concord-plugins?pullRequest=97) it.</sub>

2022-09-20 14:34 UTC, mtkunkel submitted a review, later dismissed

2022-09-22 09:30 UTC, jchikatur commented
Docs: https://github.com/walmartlabs/concord-website/pull/122

2022-10-03 14:54 UTC, mtkunkel approved these changes

2022-10-04 17:29 UTC, benbroadaway requested changes
apologies for late catch

2022-10-04 17:29 UTC, benbroadaway commented on tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/model/WatchAppResult.java
> + */
old license stuck around

2022-10-04 17:29 UTC, benbroadaway commented on tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/model/Application.java
> + */
old license stuck around

2022-10-04 17:29 UTC, benbroadaway commented on tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/model/HealthStatus.java
> + */
old license stuck around

2022-10-04 17:29 UTC, benbroadaway commented on tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/model/SyncStatus.java
> + */
old license stuck around

2022-10-06 10:34 UTC, jchikatur commented
> apologies for late catch

removed all of them. Missed them earlier

2022-10-06 12:35 UTC, benbroadaway approved these changes

2022-10-07 13:41 UTC, merged